### ISSUE TITLE
Reference implementation

### ISSUE THREAD

**Issue by bruennijs** [MapMyTracks/api#2]
Hello guys,
does anybody know whether there is an reference implementation out there? I need an opportunity to track live data by users of my own private cloud platform. I want to use an existing app (like oruxmaps) and need to receive these GPS coordinates associated to a user. 
I can also accept to integrate an external service (like MapMyTracks.com) if the service is able to push live tracking messages to my own web service. In that case my users can hand out an api token or something similar. Does anybody a solution for that?

Thanks a lot, Olli

**Comment by nicktatt** [comment]
The MMT API does not have an option to push live data to a third party. It can be used to send live data into the MMT platform but not out. Hope that helps.

**Comment by wrohdewald** [comment]
I intend to write such a thing. Right now there is https://pypi.python.org/pypi/Gpxity/. Based on that I want to write a server which emulates the MMT upload protocol. It will save the tracks locally, apply things like geofencing (remove private areas) and forward them to MMT. I am using oruxmaps.
