### ISSUE TITLE
upload_activities does not handle charsets correctly

### ISSUE THREAD

**Issue by wrohdewald** [MapMyTracks/api#21]
This is about the value for the description attribute.

The standard is very clear: The server MUST treat data as UTF-8, see https://url.spec.whatwg.org/#urlencoded-parsing.

Instead mapmytracks.com expects data encoded in ISO8859-1.

So whenever somebody uses a non-ascii character in the description, mapmytracks will show garbage.

**Comment by nicktatt** [comment]
We have made some changes to better handle this. Hope it helps.

**Comment by wrohdewald** [comment]
I think it is correct now, my tests pass.

See https://github.com/wrohdewald/Gpxity, especially the file gpxity/backends/mmt.py
