### ISSUE TITLE
stop_activity has no parameter activity_id

### ISSUE THREAD

**Issue by wrohdewald** [MapMyTracks/api#25]
That is what this API says but it seems wrong.

if the API description is actually correct, could you please specify what happens if the user has two lifetracking clients? Which one will be stopped?

**Comment by rob-tinderhouse** [comment]
For stop_activity, the system stops the activity_id held in the user's session.
We would recommend not tracking concurrent activities on the same user account.

**Comment by wrohdewald** [comment]
If tracking concurrent activities on the same user account is illegal, can you please add that to the api definition?

Otherwise I believe this will fail if the client ip address changes just before stop_activity (like when switching between LTE and Wifi).

BTW this api does not work anymore anyway at all. Try using get_activities on a free account. See my question http://support.mapmytracks.com/customer/portal/questions/17402402-did-something-change-with-api-access-
