### ISSUE TITLE
API: Export all properties of an activity

### ISSUE THREAD

**Issue by wrohdewald** [MapMyTracks/api#3]
like tags, notes, comment

**Comment by nicktatt** [comment]
We have updated get_activities to include more data. There are now also two new methods to use.

- get_activity_comments
- get_activity_tags

**Comment by wrohdewald** [comment]
This is not backwards compatible and may break applications, it certainly breaks mine. I have to do much more now for getting the full list of activities.

You could introduce a new parameter 'count' with default ALL. That would be compatible and users can still limit the amount of data if they want to.

I am currently not going to use the new attributes - I am mostly interested in the description (called "notes" at /explore/activity/#).

Getting activity tags is something I would like to use - but then I should also be able to upload them.

Right now I am using /assets/php/interface.php for changing title, activity and description. And I parse /explore/activity/# for getting those values - of course whenever you change your web pages, this might fail. Now I could use get_activities to get the current title and activity type - but as long as it works as is, I will leave this alone. I must parse /explore/activity/# anyway to get the description.

Interestingly, parsing for activity_type can result in up to 3 different values for the same activity:
in one of those places, I see the new value I just assigned, somewhere else (in the title) the old one, and in a third place it often is "Miscellaneous" instead of the correct value. Please tell me if you want to know details.
