### ISSUE TITLE
API: request=delete_activity

### ISSUE THREAD

**Issue by wrohdewald** [MapMyTracks/api#4]
would be nice to have

**Comment by nicktatt** [comment]
There is now an option to delete activities. Hope that helps.

**Comment by wrohdewald** [comment]
Helps. This is certainly more stable than what I meanwhile did instead (/user-embeds/delete-track).

Error handling does not work however:

passing 'hello' instead of a legal activity id raises no error, I stil get 'activity_deleted'

Same for existing activity ids of other accounts: The activities remain undeleted but I get 'activity_deleted'

This is a problem because I would have to try to reload the activity to really know if deletion was successful.

**Comment by nicktatt** [comment]
The error handling has now been improved.
