### ISSUE TITLE
XML data says it is utf-8 but is not

### ISSUE THREAD

**Issue by wrohdewald** [MapMyTracks/api#7]
Maybe it is iso8859-1 - at least that decodes correctly for the german umlauts I am using.

Best solution of course would be to only use utf-8 anywhere.

This is for umlauts in <title>.

Here comes a screenshot from wireshark:

![screenshot_20170201_171059](https://cloud.githubusercontent.com/assets/2433071/22515033/7dce97fe-e8a1-11e6-951b-831a98b455a0.png)

**Comment by nicktatt** [comment]
Are you still having problems with this? If so, can you provide an example request that highlights the issue?

**Comment by wrohdewald** [comment]
Yes, still the same. Look at the screenshot above: At address line 00000163 your server returns "xml version="1.0" encoding="UTF-8". But in address line 00001D3 there is HEX D6 for an Ö. This is iso8859-1 or similar. In UTF-8 this should be two bytes: HEX C3 96

The test I just did uses another title but the problem is still exactly the same. I stil need this workaround in Python3:

```
try:
    result.content.decode(result.encoding)
except  UnicodeDecodeError:
    # As of February 2017, the xml always says it is encoded as utf-8 but it is not!
    # It looks like iso8859-1
    result.encoding = result.apparent_encoding
```
(apparent_encoding is iso8859-2, see http://docs.python-requests.org/en/master/api/)

**Comment by nicktatt** [comment]
This should now work as expected.

**Comment by wrohdewald** [comment]
Works.
